title: Anthony TMFAS | Data Scientist - Python/ML Churn & NLP Expert
theme: jekyll-theme-minimal  # Clean, pro look; alternatives: architect, cayman (see pages.github.com/themes)
description: Lagos-based DS pro | WorldQuant Cert | Projects: Churn Predictor, Twitter Sentiment
